{"uuid": "b70960f1-8a1f-49c5-9340-b38a7cbaab52", "children": ["89f492ff-d530-4a4b-ac0a-5789267cafba"], "befores": [{"name": "xunit_setup_class_fixture_TestCases", "status": "broken", "statusDetails": {"message": "requests.exceptions.SSLError: HTTPSConnectionPool(host='api.test.xiangcaohuyu.com', port=443): Max retries exceeded with url: /v1/app/basic/getDeviceToken (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))\n", "trace": "  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\ybAPI\\cases\\test_02_dynamic.py\", line 30, in setup_class\n    access_token=get_token.get_user_token('13999990007','123456')\n  File \"C:\\pyapp\\app\\ybAPI\\utils\\get_token.py\", line 22, in get_user_token\n    devices_token=self.get_devices_token()\n  File \"C:\\pyapp\\app\\ybAPI\\utils\\get_token.py\", line 17, in get_devices_token\n    devices_token=requests.post(url,files=public_params)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\requests\\api.py\", line 116, in post\n    return request('post', url, data=data, json=json, **kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\requests\\api.py\", line 60, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\requests\\sessions.py\", line 524, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\requests\\sessions.py\", line 637, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\requests\\adapters.py\", line 514, in send\n    raise SSLError(e, request=request)\n"}, "start": 1634899945153, "stop": 1634899945240}], "start": 1634899945153, "stop": 1634899945344}